/**
 * The Ed25519 PUBLIC key. Generated by tools/make-keypair.ts — do not edit by hand.
 *
 * This is safe to ship: it can only VERIFY licences, never mint them. The matching PRIVATE key
 * lives with the vendor at ~/.insha-pos-keys/license-private.pem and must NEVER enter this repo.
 */
export const LICENSE_PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEA1mQt2YrIMpFqqvg4k+mBDxK1XpU8O2MtvlZBffxR0Lo=
-----END PUBLIC KEY-----`
