/**
 * ONE-TIME vendor setup. Creates the Ed25519 licence keypair.
 *
 *   npm run make:keypair
 *
 * ┌──────────────────────────────────────────────────────────────────────────────┐
 * │  THE PRIVATE KEY IS THE PRODUCT.                                             │
 * │                                                                              │
 * │  Anyone holding it can mint unlimited licences for every copy of this app,   │
 * │  forever. It is written OUTSIDE the repo (~/.insha-pos-keys/), it is in      │
 * │  .gitignore, and it must be BACKED UP somewhere safe — a password manager.   │
 * │  Lose it and you can never issue or renew a licence for an existing customer │
 * │  again without shipping a new build with a new public key.                   │
 * │                                                                              │
 * │  The PUBLIC key is written into the app's source. That one is harmless.      │
 * └──────────────────────────────────────────────────────────────────────────────┘
 *
 * `tools/` is maintainer-only and is NOT shipped in the installer.
 */
import { generateKeyPairSync } from 'node:crypto'
import { writeFileSync, mkdirSync, existsSync, chmodSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'

const KEY_DIR = join(homedir(), '.insha-pos-keys')
const PRIVATE_PATH = join(KEY_DIR, 'license-private.pem')
const PUBLIC_PATH = join(KEY_DIR, 'license-public.pem')
const EMBED_PATH = join(process.cwd(), 'src', 'main', 'security', 'public-key.ts')

if (existsSync(PRIVATE_PATH)) {
  console.error(`\n  REFUSING TO OVERWRITE an existing private key at:\n    ${PRIVATE_PATH}\n`)
  console.error('  Overwriting it would invalidate every licence you have ever issued.')
  console.error('  Delete it by hand only if you are certain no customer is relying on it.\n')
  process.exit(1)
}

const { publicKey, privateKey } = generateKeyPairSync('ed25519')

const privatePem = privateKey.export({ type: 'pkcs8', format: 'pem' }).toString()
const publicPem = publicKey.export({ type: 'spki', format: 'pem' }).toString()

mkdirSync(KEY_DIR, { recursive: true })
writeFileSync(PRIVATE_PATH, privatePem, { mode: 0o600 })
chmodSync(PRIVATE_PATH, 0o600) // owner-read-only
writeFileSync(PUBLIC_PATH, publicPem)

writeFileSync(
  EMBED_PATH,
  `/**
 * The Ed25519 PUBLIC key. Generated by tools/make-keypair.ts — do not edit by hand.
 *
 * This is safe to ship: it can only VERIFY licences, never mint them. The matching PRIVATE key
 * lives with the vendor at ~/.insha-pos-keys/license-private.pem and must NEVER enter this repo.
 */
export const LICENSE_PUBLIC_KEY = \`${publicPem.trim()}\`
`
)

console.log(`
  Keypair created.

  PRIVATE (never commit, back this up):  ${PRIVATE_PATH}
  PUBLIC  (copy kept for reference):     ${PUBLIC_PATH}
  EMBEDDED into the app:                 ${EMBED_PATH}

  Back up the private key now. Without it you cannot renew a customer's licence.
`)
